import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

function App(){
 const [data,setData]=useState({lists:[],tasks:[]}), [listId,setListId]=useState(null), [selected,setSelected]=useState(null);
 const [tab,setTab]=useState('list'), [filter,setFilter]=useState('all'), [title,setTitle]=useState(''), [newList,setNewList]=useState('');
 const [draft,setDraft]=useState(null), [error,setError]=useState(''), [busy,setBusy]=useState(false), [loading,setLoading]=useState(true), [drag,setDrag]=useState(null), [message,setMessage]=useState('');
 async function api(path,method='GET',body){const res=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!res.ok){let details=await res.json().catch(()=>({}));throw Error(typeof details.detail==='string'?details.detail:'Unable to save. Check your entries and try again.')}return res.json()}
 async function load(){const state=await api('/state');setData(state);setListId(old=>state.lists.some(l=>l.id===old)?old:state.lists[0]?.id??null)}
 useEffect(()=>{load().catch(()=>setError('Cannot connect to the server. Check that the app is running, then retry.')).finally(()=>setLoading(false))},[]);
 async function run(action){setBusy(true);setError('');setMessage('');try{await action();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const list=data.lists.find(l=>l.id===listId), tasks=data.tasks.filter(t=>t.list_id===listId), done=tasks.filter(t=>t.completed).length;
 const visible=tasks.filter(t=>filter==='all'||(filter==='completed'?t.completed:!t.completed));
 const original=data.tasks.find(t=>t.id===selected);
 const dirty=draft&&original&&(draft.title!==original.title||draft.note!==original.note||draft.list_id!==original.list_id||draft.completed!==original.completed);
 function leave(){return !dirty||confirm('Discard your unsaved changes?')}
 function choose(id){if(!leave())return;setListId(id);setTab('list');setDraft(null);setSelected(null)}
 function open(task){if(!leave())return;setSelected(task.id);setDraft({...task});setTab('description')}
 useEffect(()=>{function unload(e){if(dirty){e.preventDefault();e.returnValue=''}}window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[dirty]);
 function move(id,target){if(busy||id===target)return;const ids=tasks.map(t=>t.id),from=ids.indexOf(id),to=ids.indexOf(target);if(from<0||to<0)return;ids.splice(to,0,ids.splice(from,1)[0]);run(()=>api(`/lists/${listId}/order`,'PUT',{ids}))}
 async function add(e){e.preventDefault();if(!title.trim()||!listId)return;await run(async()=>{await api('/tasks','POST',{title:title.trim(),list_id:listId});setTitle('')})}
 return <div className="app"><aside><a className="brand" href="/"> <span className="logo">✓</span> daylight<span className="dot">.</span></a><div className="side-label">YOUR SPACE</div><h2>My lists <span>{data.lists.length}</span></h2><nav>{data.lists.map(l=><button key={l.id} className={'list-link '+(listId===l.id?'chosen':'')} onClick={()=>choose(l.id)}><span>▤</span><span>{l.name}</span><b>{data.tasks.filter(t=>t.list_id===l.id&&!t.completed).length}</b></button>)}</nav>{<form className="new-list" onSubmit={e=>{e.preventDefault();run(async()=>{const l=await api('/lists','POST',{name:newList.trim()});setNewList('');if(leave()){setListId(l.id);setTab('list');setDraft(null);setSelected(null)}})}}><input aria-label="New list name" placeholder="Name a new list" maxLength={100} value={newList} onChange={e=>setNewList(e.target.value)}/><button disabled={busy||!newList.trim()} aria-label="Add list">+</button></form>}<div className="side-bottom"><span className="sun">☀</span><p>A little progress,<br/>every day.</p><small>Your space to get things done.</small></div></aside>
 <main><header><span>SHARED WORKSPACE</span><span className="date">{new Intl.DateTimeFormat('en',{month:'long',day:'numeric',year:'numeric'}).format(new Date())}</span></header><section className="heading"><div><p className="eyebrow">MAKE ROOM FOR WHAT MATTERS</p><h1>{list?.name||'A fresh start'}</h1><p>{tasks.length?`${tasks.length-done} tasks left. One step at a time.`:'Big plans start with one small task.'}</p></div><div className="progress"><strong>{done}<span> / {tasks.length}</span></strong><small>tasks completed</small><progress max={tasks.length||1} value={done}/></div></section>
 <div className="access-bar"><span>Shared workspace · Anyone can add, edit, and delete tasks</span></div>
 <div className="tabs" role="tablist" aria-label="Task views"><button role="tab" aria-selected={tab==='list'} onClick={()=>{if(leave()){setTab('list');setDraft(null)}}}>☷ &nbsp; To-Do List</button><button role="tab" aria-selected={tab==='description'} onClick={()=>setTab('description')}>▧ &nbsp; Task Description</button></div>
 {error&&<div role="alert" className="error">{error} <button disabled={busy} onClick={()=>run(load)}>Retry</button></div>}<div role="status" className="status">{message}</div>
 {loading?<div className="empty">Loading your workspace…</div>:tab==='list'?<section aria-label="To-Do List"><div className="toolbar"><div className="filters">{[['all','All tasks',tasks.length],['active','Active tasks',tasks.length-done],['completed','Completed',done]].map(([key,label,count])=><button key={key} aria-pressed={filter===key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label} <span>{count}</span></button>)}</div>{list&&<div className="list-actions"><button disabled={busy} onClick={()=>{const name=prompt('Rename list',list.name);if(name?.trim())run(()=>api(`/lists/${listId}`,'PUT',{name:name.trim()}))}}>Rename list</button><button disabled={busy} className="danger" onClick={()=>{if(confirm(`Delete “${list.name}” and all ${tasks.length} tasks? This cannot be undone.`))run(()=>api(`/lists/${listId}`,'DELETE'))}}>Delete list</button></div>}</div>
 {<form className="add-task" onSubmit={add}><span>+</span><input aria-label="New task" placeholder={list?'What would you like to get done?':'Create a list to add your first task'} maxLength={200} disabled={!list} value={title} onChange={e=>setTitle(e.target.value)}/><button className="primary" disabled={busy||!title.trim()||!list}>Add task <span>↵</span></button></form>}
 <div className="task-list">{visible.map(task=><article key={task.id} draggable={!busy&&filter==='all'} onDragStart={()=>setDrag(task.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(filter==='all')move(drag,task.id);setDrag(null)}} className={'task '+(task.completed?'finished':'')}>{<span className="grip" aria-hidden="true">⠿</span>}<input type="checkbox" aria-label={`Complete ${task.title}`} checked={task.completed} disabled={busy} onChange={()=>run(()=>api(`/tasks/${task.id}`,'PUT',{...task,completed:!task.completed}))}/><button className="task-title" onClick={()=>open(task)}><strong>{task.title}</strong><small>{task.note?task.note:'Add a description or note'}</small></button>{<div className="row-actions"><button title="Move up" aria-label={`Move ${task.title} up`} disabled={busy||filter!=='all'||tasks[0]?.id===task.id} onClick={()=>move(task.id,tasks[tasks.findIndex(t=>t.id===task.id)-1]?.id)}>↑</button><button title="Move down" aria-label={`Move ${task.title} down`} disabled={busy||filter!=='all'||tasks.at(-1)?.id===task.id} onClick={()=>move(task.id,tasks[tasks.findIndex(t=>t.id===task.id)+1]?.id)}>↓</button><button onClick={()=>open(task)} aria-label={`Edit ${task.title}`}>✎</button><button className="danger" aria-label={`Delete ${task.title}`} onClick={()=>{if(confirm(`Delete “${task.title}”?`))run(()=>api(`/tasks/${task.id}`,'DELETE'))}} disabled={busy}>×</button></div>}</article>)}</div>
 {!visible.length&&<div className="empty"><span>✓</span><h3>{filter==='completed'?'Your wins will live here':filter==='active'&&tasks.length?'All caught up!':'Room for your next idea'}</h3><p>{filter==='completed'?'Check off a task to see it here.':'Add a task above and take the first step.'}</p></div>}<footer><span>{visible.length} {visible.length===1?'task':'tasks'} shown</span><span>{filter==='all'?'Drag tasks or use ↑ ↓ to reorder':'Select All tasks to reorder'}</span></footer></section>:<section className="details">{draft?<form onSubmit={e=>{e.preventDefault();run(async()=>{const saved=await api(`/tasks/${draft.id}`,'PUT',draft);setDraft(saved);setListId(saved.list_id);setMessage('Changes saved.')})}}><div className="detail-heading"><h2>Make the next step clear.</h2><span>{dirty?'Unsaved changes':'Saved'}</span></div><label>Task name<input required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description & notes<textarea rows={8} maxLength={20000} placeholder="Ideas, details, or the steps to get it done…" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="detail-bottom"><label>{'Move to list'}<select value={draft.list_id} onChange={e=>setDraft({...draft,list_id:Number(e.target.value)})}>{data.lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={draft.completed} onChange={e=>setDraft({...draft,completed:e.target.checked})}/>Completed</label></div><div className="save-actions"><button type="button" onClick={()=>{if(leave()){setDraft(null);setTab('list')}}}>Back to list</button>{<button className="primary" disabled={busy||!draft.title.trim()}>{busy?'Saving…':'Save changes'}</button>}</div></form>:<div className="empty"><span>▧</span><h3>A little more detail</h3><p>Select a task in the To-Do List to read its description and notes.</p><button className="primary" onClick={()=>setTab('list')}>Go to tasks</button></div>}</section>}
 <div className="bottom-note">Small steps. Clear mind.</div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
